### ISSUE TITLE
mouse::smooth_move is either wrong of unecessarily complicated

### ISSUE THREAD

**Issue by tafia** [autopilot-rs/autopilot-rs#2]
Great lib! I haven't really tried it but I see lot of potential.

I have read a little into the code and I must confess I don't fully understand the implementation for `mouse::smooth_move`.

I believe that it is very complicated for what it does, there may be some reasons that I don't understand. 

### rand

You shouldn't initalize a new `thread_rng` everytime

```rust
let rng = rand::thread_rng();
while (...) {
// ...
        let gravity: f64 = rng.gen_range(5.0, 500.0);
// ...
        let duration: u64 = rng.gen_range(1, 3);
        std::thread::sleep(std::time::Duration::from_millis(duration));
}
```

### velo.x and velo.y

If I take the hypothesis that `hypo(x, y) = sqrt(x2 + y2)`.

First, `velo_distance` can be simplified to `gravity`:

```rust
// let:
// dx = pos.x - dest.x, 
// dy = pos.y - dest.y
// d = sqrt(dx2 + dy2)

v = velo_distance 
= sqrt(velo.x2 + velo.y2)
= sqrt(gravity2 * dx2 / d2 + gravity2 * dy2 / d2)
= gravity/d * sqrt(dx2 + dy2)
= gravity
```

Then if you normalize v ...

```rust
vx => vx / v
= (gravity * dx / d) / gravity
= dx / d

// and similarly
vy = dy / d
```

... so to conclude **you don't even need the random values** (`gravity`) for the update, the variable thread sleep is enough to give that feeling of randomness ...

**Comment by msanders** [comment]
Thanks for the thoughtful feedback @tafia. I've updated this function to be a bit simpler: https://github.com/autopilot-rs/autopilot-rs/commit/2fa85789064cb7f8fee9345e19dfe5cd4dc3fd4f.
