### ISSUE TITLE
[Question] Easy way to do same automation in multiple times?

### ISSUE THREAD

**Issue by shirshak55** [autopilot-rs/autopilot-rs#21]
Is there any easy way to do gui automation easily for multiple time for same app in parallel or concurrently?

Currently what is do is create multiple users etc. That seems abit tedious right? If there is better way let me know :)

Thanks.

**Comment by msanders** [comment]
I'm not sure this is possible aside from using VMs. The OS needs to gain focus of the mouse/keyboard so that has to be done synchronously as far as I'm aware.

**Comment by shirshak55** [comment]
Yea using vm is possible but booting vm etc takes so much unnecessary resource I think there should be some easy way :(

**Comment by msanders** [comment]
What are you doing currently with multiple users? The only other thing I can think of is maybe running multiple instances of X11 but not sure how feasible that is (not very familiar with X).

**Comment by shirshak55** [comment]
@msanders For automation bro. most of the windows app don't supply automation. Like for game I want to test out by playing chess etc. However I cannot dedicate on full vm just for playing chess. Thats just a simple example I do have many apps which I would like to automate.

**Comment by shirshak55** [comment]
And I think we can close this issue if you think that we cannot move forward as I also understand its really hard to do it. in Windows we can make different user use Remote desktop protocol and do it. In Linux we can create different account and dedicate a task but I think its overly complicated right.

**Comment by msanders** [comment]
Sounds good, closing this for now. Your approach sounds reasonable and is probably what I would go with as well.
