### ISSUE TITLE
key::tap triple delay when using flags

### ISSUE THREAD

**Issue by Zeldern** [autopilot-rs/autopilot-rs#24]
When using ```autopilot::key::tap(&Character('c'), &[autopilot::key::Flag::Alt], 25);``` you'll get a total delay of 75ms, 25 for the "tap" and an extra 25 for each use of the modifier (down and up). Is this intentional behaviour?

I would've thought there would just be a 25ms delay between the use of c + modifier down and c + modifier up.

**Comment by msanders** [comment]
This should probably be an additional parameter in that function (`modifier_delay_ms`). IIRC it's neccessary on certain platforms for the tap to register.
