### ISSUE TITLE
Q: AutoPilot and AutoPy relations

### ISSUE THREAD

**Issue by banderlog** [autopilot-rs/autopilot-rs#25]
Hi, I'm confused, in `README.md` you stated that:
>AutoPilot is a Rust port of the Python C extension AutoPy, a simple, cross-platform GUI automation library for Python. For more information, see the README on that repo.

But AutoPy, which is also your project,  just python wrapper around AutoPilot.

So is it true, that you wrote autopilot and than autopy? Or you wrote autopy on C++, than ported it to rust than used it in autopy?

PS: They both  have first commits in Oct 2017.

**Comment by msanders** [comment]
AutoPy was originally written in C. The original extension is [here](https://github.com/autopilot-rs/autopy-legacy). I can see how that could be confusing though, should probably reword the doc.

**Comment by banderlog** [comment]
Aha, I see now :)
