### ISSUE TITLE
Relicense under dual MIT-or-Apache-2.0

### ISSUE THREAD

**Issue by msanders** [autopilot-rs/autopilot-rs#26]
I'd like to relicense this project from Apache 2.0 to an MIT-or-Apache dual license for consistency with the Rust community, and to allow GPLv2 compatibility, which I was previously unaware was disallowed by Apache.

For more information, see [the explainer text used when the community switched over](https://github.com/cmr/relicense-assistant/blob/f5c0a2922a98a74e4d555848f9b72a81dd19b38d/issue-template.txt#L14), or one of the many [automatically generated issues](https://github.com/sfackler/rust-postgres-macros/issues/19) on popular projects.

To do this, it’s necessary to get explicit approval from each contributor (aside from small typo fixes, etc., as described in the above links). I’ve cc’d everyone here and will be checking off boxes as people show up.

- [x] @msanders
- [x] @greizgh
- [x] @rlewismd
- [ ] ~~@zrnsm~~ (n/a)
- [x] @waywardmonkeys
- [x] @pheki
- [x] @murlakatamenka
- [x] @VojtechStep
- [x] @Ivshti

To agree to relicensing, please comment with:

> I license past and future contributions under the dual MIT-or-Apache-2.0 license, allowing licensees to choose either at their option.

(Feel free to unsubscribe from this issue after leaving your comment.)

Once everyone has commented, I'll open a PR making the change. Will be doing this for the sister projects here as well.

Thanks your help!

**Comment by msanders** [comment]
I license past and future contributions under the dual MIT-or-Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by VojtechStep** [comment]
I license past and future contributions under the dual MIT-or-Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by murlakatamenka** [comment]
I license past and future contributions under the dual MIT-or-Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by greizgh** [comment]
I license past and future contributions under the dual MIT-or-Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by rlewismd** [comment]
I license past and future contributions under the dual MIT-or-Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by waywardmonkeys** [comment]
I license past and future contributions under the dual MIT-or-Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by pheki** [comment]
I license past and future contributions under the dual MIT-or-Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by svanellewee** [comment]
I license past and future contributions under the dual MIT-or-Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by msanders** [comment]
The remaining two contributions are small typo fixes [both under 15 lines](https://www.gnu.org/prep/maintain/html_node/Legally-Significant.html) so I'm comfortable moving forward:

- @Ivshti: https://github.com/autopilot-rs/autopilot-rs/commit/3f48726d23ef50f2699becdb1d6a5f212d22e905
- @zrnsm: https://github.com/autopilot-rs/autopilot-rs/commit/39a551a452d3bbfaf2dac4aa200f815ad794c09d

Tried reaching out over email but didn't receive a response. Will be putting up a PR shortly.

**Comment by Ivshti** [comment]
I’m OK with it 👍 haven’t received anything though

**Comment by msanders** [comment]
:+1: sounds good, thanks Ivo!
