### ISSUE TITLE
Build failure on mac: Insert key missing

### ISSUE THREAD

**Issue by mitizhi** [autopilot-rs/autopilot-rs#42]
`cargo build` fails on Mac (macOS Mojave 10.14.6, so I am lacking behind):

    error[E0004]: non-exhaustive patterns: `Insert` not covered
       --> src/key.rs:323:15
        |
    43  | / pub enum KeyCode {
    44  | |     F1,
    45  | |     F2,
    46  | |     F3,
     ...  |
    79  | |     Insert,
        | |     ------ not covered
    ...   |
    107 | |     NumEnter,
    108 | | }
        | |_- `key::KeyCode` defined here
     ...
    323 |           match code {
        |                 ^^^^ pattern `Insert` not covered
        |
           = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
           = note: the matched value is of type `key::KeyCode`

    error: aborting due to previous error

    For more information about this error, try `rustc --explain E0004`.
    error: could not compile `autopilot`

    To learn more, run the command again with --verbose.
    warning: build failed, waiting for other jobs to finish...
    error: build failed

Mac keyboards do not have Insert key. This maybe explains why my `core_graphics` package does not include the definition of that key so I am not able to add it. When I just brutally removed the offending "Insert" from `enum KeyCode` (src/key.rs:82) then the build succeeded on my Mac. This obviously is not the way to fix the issue, so I am not submitting a pull request... ;-)

**Comment by msanders** [comment]
Thanks for the report. Fixed by #37.
