### ISSUE TITLE
Speed up functions calling key::tap()

### ISSUE THREAD

**Issue by ryansname** [autopilot-rs/autopilot-rs#5]
When calling `key::type_string` with 0wpm I was expecting there to be almost no delay in my string being typed, however it proceeded to type at a very human speed.

I was wondering if you'd be interested in a PR that allows for super fast typing when calling `key::type_string` and similar functions with 0wpm by removing the random delay here (by boolean, or chars per minute + noise args): https://github.com/autopilot-rs/autopilot-rs/blob/0607d08b43411cb7d55dc06c060cbce5da119eb5/src/key.rs#L119

ie:
`pub fn tap<T: KeyCodeConvertible + Copy>(key: T, char_per_minute: Option<u64>, noise: Option<f32>, flags: &[Flag]) {`
or
`pub fn tap<T: KeyCodeConvertible + Copy>(key: T, include_toggle_delay: bool, flags: &[Flag]) {`

Alternatively is there a reason or OS that is causing this delay to be required, it seemed to work OK in my limited trial where I commeted that part out?

Thanks

**Comment by msanders** [comment]
That's a good point, this should probably be configurable. I like the idea you stated of passing in `noise` (or perhaps just an explicit interval) as another argument.

`pub fn tap<T: KeyCodeConvertible + Copy>(key: T, delay: Option<f32>, flags: &[Flag])`

Then when calling it from `type_string` just divide `ms_per_character` in half when calling tap. We can probably default to a delay of zero. I'll test to make sure it doesn't cause issues across different OSes.

Definitely open to contributions if you're interested!
